In [1]:
import os
import numpy

In [2]:
file_location = os.path.join('data', 'water.xyz')

In [3]:
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)

In [4]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [5]:
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]

In [6]:
coordinates = coordinates.astype(numpy.float)

<ipython-input-6-658249c90a51>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coordinates = coordinates.astype(numpy.float)


In [7]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [14]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        #print(num1,num2)
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f, <1.5}')

ValueError: Invalid format specifier

In [13]:
# Modify my code to only print atoms that are bonding
# Rule: Distance between atoms is less than 1.5 angstroms


In [22]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        #print(num1,num2)
        if num1<num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance > 0 and distance < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


## Writing and Using Functions

In [23]:
#def function_name(parameters):
#    ** body of your function **
#    ** write code using the parameters to calculate something**
#    return value_to_return

In [26]:
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [27]:
calculate_distance([0, 0, 0], [0, 0, 1])

1.0

In [28]:
calculate_distance([0, 0, 0], [1, 1, 1])

1.7320508075688772

In [29]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        #print(num1,num2)
        if num1<num2:
            distance = calculate_distance(coordinates[num1],coordinates[num2])
        
            if distance > 0 and distance < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [30]:
# Write a function to check and see if a distance is a bond
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance < 1.5:
        return True
    else:
        return False

In [31]:
bond_check(1.7)

False

In [32]:
bond_check(1.2)

True

In [33]:
bond_check(-50)

False

In [34]:
# Modify the bond check function to take a minimum and a maximum length as an input

In [38]:
def bond_check(atom_distance, minimum_length=0, maximum_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False

In [36]:
bond_check(1.7,0,2.0)

True

In [41]:
Help on function bond_check in module _main_:

SyntaxError: invalid syntax (<ipython-input-41-46dc0b64e30a>, line 1)

In [44]:
num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        #print(num1,num2)
        if num1<num2:
            distance = calculate_distance(coordinates[num1],coordinates[num2])
            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [46]:
# Write a new function called open_xyz that opens and processes an xyz file.
# Your function should accept a filepath for the input

In [47]:
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats
    """
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coord = xyz_file[:,1:]
    coord = coord.astype(numpy.float)
    return symbols, coord


In [52]:
import os
import numpy

def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

def bond_check(atom_distance, minimum_length=0, maximum_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False
    
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats
    """
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coord = xyz_file[:,1:]
    coord = coord.astype(numpy.float)
    return symbols, coord

file_location = os.path.join('data','water.xyz')
symbols, coordinates = open_xyz(file_location)
num_atoms = len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
            distance = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


<ipython-input-52-df83a932f4b3>:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coord = coord.astype(numpy.float)
